version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
       - "3000:9080"
    image: dropbox-tags-wlp
    environment:
       - DBX_ACCESS_TOKEN=
       - SOLR_URL=
       - ZIP_MAX_SIZE=
