version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
       - "3000:9080"
    image: dropbox-tags-wlp
    environment:
       - DBX_ACCESS_TOKEN=[enter your dropbox access token here]
       - SOLR_URL=[enter solr url here]
       - ZIP_MAX_SIZE=[enter zip max size here]
